### ISSUE TITLE
Link to VistSOS show case not found

### ISSUE THREAD

**Issue by ninsbl** [istSOS/VistSOS#2]
The link to the VistSOS showcase in the wiki:
http://131.175.143.71/vistsos/test/showcase/#line
 is not found / working....

**Comment by andres-fps** [comment]
The link to the showcase was fixed.

**Comment by ninsbl** [comment]
Yes, it is fixed here:
https://github.com/felipe07/VistSOS-1/wiki
but not yet here:
https://github.com/istSOS/VistSOS/wiki

**Comment by andres-fps** [comment]
Since I can't commit to https://github.com/istSOS/VistSOS/ a pull request was created to merge both repositories. I will update the issue as soon as it's done.

**Comment by ninsbl** [comment]
Fixed with #3

**Comment by ninsbl** [comment]
Thanks!
